apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
    spec:
      containers:
        - name: guestbook-ui
          resources:
            requests:
              cpu: 1000m
              memory: 256Mi
