apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: guestbook-ui-secret
  namespace: test-ns
spec:
  encryptedData:
    password: AgBs4sv9mMRynIlw6hGaM2IW7v8gd4Iu5cvtlF2QaojFkk96BW1PXXs7b2jmEIpPuyjLJh2DVLJonfl2ATklVyaFviqMLj0Bryz4tuGqKGYZJLs6n5ysf0fguB1FxWUSRPDvpMOicY7pizf41dOCjd4t6pygF2ZtGxJbEI2ekZZiI9im1tJM4KgNjVHt8d0BX88k4B4pzhQ3aspPg05FvlkyBnZNAATMTk7t2px26EV3QEx+ToYWBiXBT95yKJsF/zrTvnMt4mCvTkDthIYF+t2Ra+2V8MMkdwHkzNMVafsEzBNTHV70m3BgYnqRAd2h74O6tK/Se2K0hJoM9liH8eVpXCDk5qRCFf5AbVejf4ynZf8kwSGsqjHkaCf8ATy5VxuvdDEPun8O56A1HFKSoSSJ1ZEu1sZBvjtXlvHBbTeRx8OpF9ngdYmwuLGNQcdP+/EkQbwT/OVQEOmsCAR4D+drPOQ8tbxa5fosz0gnhqscvWxrV7VQZ9yFT6EaKvcKzzrlB22aA7fM46nimXFB0inIXbxXhoIxT3CFwu2STBp5OAHOgw1WV7h6BzLvAEbZTZjw0G8J8CqJ4DDNtWBTFKdXHazvnzNDOHSDhbVwk8X8NmRlcrxgeCcl9VuZJCcKZ7nuUOPiLZT/iyoG5oFzjQfQEXBf+IQiZqLAXI1RIUBy3L5ULKSPwUoLZ2IAdKu0WzZpDeAYeQFEuc0Bi1M=
    username: AgBgsfbxL719qL/56LXUpu9AEec/thX/YsH0nfx6OXWfqmIbYVgTi6ZRZB6VHwoXBq2zJZGDh7vPKWRU+o5SAZEtpD3rdvNbByigRpaHvICevjiSMaG0BXKGn9o43MGdoh/og1Tsbb+1nuGknris+qNxRPY7sUJeZuM8RieiwL2ml/u3Ct+cymwd+aMbdDSh+bLudZcazVz1iZQUpH/hJGI1YH0S3yqJRO7pK3mMaW/FV19fw5XLjs6sClQBGnGtpHxekQbsrEoyCpBn6gLHi5ezpMrxXOkmm9iAuASnSrjdHwBYIZTB/Len8/SSFrD4mUBQtRec0QTyKmsx8g4zIVuyY7LOaVNaJNSik9o0aJbtoJPpxNfuPS27xBGKz00KfPELTR+FJyjTwsw6fss34fICiAX15lwFGTehRYGFmHy9uybajHgUTR3ucMUBPGO4DIxXFoWCZnlMJ2qzA7gQ4gqeRj5Jtt5k/isSq1za3+zut830mD1SWN7uZBQibdDbUgh0H+jqQA0ZbdbCe7/BoOkOVghQ8pcdG4DByO6EG0YH7NsA3yKbAqjxWCUMGeXs7MWjgCZmnIMd9R1lKkC/g5GnJU3CrzNBpYis1Uf4rTkTvnlgd3svgcdA3ipnCgLoi3Ltio1e8/l7UdFRCuFyC5U9wKPpFI7d5Z8IjpJ4K4L6nyJLbG9Dkx6YqJCABdLBIpp6ouLubg==
  template:
    metadata:
      creationTimestamp: null
      name: guestbook-ui-secret
      namespace: test-ns
    type: Opaque
status: {}

