apiVersion: "soluto.com/v1alpha1"
kind: KamusSecret
metadata:
  name: test-kamus-secret
  namespace: test-ns
type: TlsSecret
data:
  key: q9n4zB8ixjVIS8AOLmpp5w==:5cMI0SGYBoff8J4EA6FZHQ==
serviceAccount: kamus-example-sa
