namePrefix: kustomize-

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: mysecrets
  envs:
  - foo.env
  literals:
  - FRUIT=apple
  - VEGETABLE=carrot