apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: namespace
  namespace: argocd
spec:
  description: namespace AppProject manage namespaces for applications

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy

  orphanedResources:
    warn: false
