namePrefix: prod-
commonLabels:
  variant: prod

bases:
- ../../base

patches:
- replica_count.yaml

# secretGenerator:
# - name: guestbook-ui
#   # paths to files with k=v pairs, one pair per line.
#   env: config/guestbook-ui-secret.txt
#   type: Opaque
