name: k3s-action

on: [pull_request]

jobs:
  run-guestbook-on-k3s:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to master
        uses: actions/checkout@v1
        with:
          ref: master
      - name: set up k3s
        run: curl -sfL https://get.k3s.io | sh -
      - name: set kubeconfig
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        run: sudo mkdir ~/.kube && sudo cp ${KUBECONFIG} ~/.kube/config
      - name: test
        run: |
          sleep 10
          sudo kubectl get nodes
          sudo kubectl get pod -A
      - name: deploy guestbook
        run: |
          sudo kubectl apply -f namespace/test-ns.yaml
          sudo kubectl apply -f apps/guestbook/
          sudo kubectl get pod -n test-ns
      - name: checkout to current branch
        uses: actions/checkout@v1
      - name: diff
        run: |
          echo "```diff" >> comments
          sudo kubectl diff -f apps/guestbook/ || true >> comments
          echo "```" >> comments
          sed -i -z 's/\n/\\n/g' comments

      - name: Post multi-line comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.comments_url }}
        run: |
          curl -X POST \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              -d "{\"body\": \"$(cat comments)\"}" \
              ${URL}
